version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi-admin
    healthcheck:
      test: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
  api:
    build: .
    container_name: api
    #tty: true
    #volumes:
    #  - ./examples:/examples
    restart: always
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/fastapi-admin
      TZ: Asia/Shanghai
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    image: fastapi-admin
    command: uvicorn examples.main:app --port 3000 --host 0.0.0.0
    #command: uvicorn main:examples --port 8000 --host 0.0.0.0
